# Generated by Django 6.1 on 2026-08-19 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0002_route_shipment_shipmentstatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.PositiveIntegerField(help_text='Sequence order of the stop (1, 2, 3...)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.CharField(blank=True, help_text='Special delivery instructions for driver', max_length=255, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='fleet_management.route')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='fleet_management.shipment')),
            ],
            options={
                'ordering': ['stop_number'],
                'unique_together': {('route', 'stop_number')},
            },
        ),
    ]
