# Generated by Django 6.1 on 2026-08-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0003_routestop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestop',
            options={'ordering': ['stop_number', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'shipment')},
        ),
    ]
